#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

# FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
# WORKDIR /
# EXPOSE 80
# EXPOSE 443

# FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
# WORKDIR /
# COPY ["Minimal.Api.Structured/Minimal.Api.Structured.csproj", "Minimal.Api.Structured/"]
# COPY ["Minimal.Api.Common/Minimal.Api.Common.csproj", "Minimal.Api.Common/"]

# RUN dotnet restore "Minimal.Api.Structured/Minimal.Api.Structured.csproj" --verbosity diag
# COPY . .
# WORKDIR "/Minimal.Api.Structured"
# RUN dotnet build "Minimal.Api.Structured.csproj" -c Release -o /app/build

# FROM build AS publish
# RUN dotnet publish "Minimal.Api.Structured.csproj" -c Release -o /app/publish

# FROM base AS final
# WORKDIR /app
# COPY --from=publish /app/publish .
# ENTRYPOINT ["dotnet", "Minimal.Api.Structured.dll"]

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /
COPY ["Minimal.Api.Controllers/Minimal.Api.Controllers.csproj", "Minimal.Api.Controllers/"]
COPY ["Minimal.Api.Common/Minimal.Api.Common.csproj", "Minimal.Api.Common/"]
RUN dotnet restore "Minimal.Api.Controllers/Minimal.Api.Controllers.csproj"
COPY . .
WORKDIR "/Minimal.Api.Controllers"
RUN dotnet build "Minimal.Api.Controllers.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Minimal.Api.Controllers.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Minimal.Api.Controllers.dll"]